-- MySQL Script generated by MySQL Workbench
-- Thu 05 Jul 2018 08:09:21 PM -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eqson
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eqson
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eqson` DEFAULT CHARACTER SET utf8 ;
USE `eqson` ;

-- -----------------------------------------------------
-- Table `eqson`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqson`.`Producto` (
  `Marca` VARCHAR(20) NOT NULL,
  `Modelo` VARCHAR(20) NOT NULL,
  `Imagen` LONGBLOB NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  `Especificaciones` VARCHAR(400) NULL,
  `PrecioCompra` DECIMAL(15,2) NOT NULL,
  `PrecioVenta` DECIMAL(15,2) NOT NULL,
  `Stock` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Marca`, `Modelo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `eqson`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqson`.`Usuario` (
  `nombre` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(200) NULL,
  `esAdmin` TINYINT NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `eqson`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqson`.`Compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `eqson`.`ventaProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqson`.`ventaProducto` (
  `marcaProducto` VARCHAR(20) NOT NULL,
  `modeloProducto` VARCHAR(20) NOT NULL,
  `idCompra` INT NOT NULL,
  INDEX `fk_ventaProducto_2_idx` (`idCompra` ASC),
  INDEX `fk_ventaProducto_1_idx` (`marcaProducto` ASC, `modeloProducto` ASC),
  CONSTRAINT `fk_ventaProducto_1`
    FOREIGN KEY (`marcaProducto` , `modeloProducto`)
    REFERENCES `eqson`.`Producto` (`Marca` , `Modelo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ventaProducto_2`
    FOREIGN KEY (`idCompra`)
    REFERENCES `eqson`.`Compras` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `eqson`.`listaProductos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqson`.`listaProductos` (
  `nombreUsuario` VARCHAR(20) NOT NULL,
  `idCompra` INT NOT NULL,
  INDEX `fk_listaProductos_1_idx` (`nombreUsuario` ASC),
  INDEX `fk_listaProductos_2_idx` (`idCompra` ASC),
  CONSTRAINT `fk_listaProductos_1`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `eqson`.`Usuario` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_listaProductos_2`
    FOREIGN KEY (`idCompra`)
    REFERENCES `eqson`.`Compras` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
